# Uncomment this line to define a global platform for your project

# Uncomment this line if you're using Swift
platform :ios, '10.0'
use_frameworks!

target 'DY' do

# Alamofire 网络库
pod 'Alamofire', '~> 4.0'

end

